# Generated by Django 5.0.6 on 2024-07-06 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sayohat_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aviakompaniya', models.CharField(max_length=100)),
                ('davomiyligi', models.IntegerField()),
                ('ovqatlanish', models.CharField(max_length=100)),
                ('viza', models.BooleanField()),
                ('bonuslar', models.TextField()),
                ('sayohat_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.sayohat_turi')),
            ],
        ),
    ]
